python mnist_batch_size.py --batch_size=5 --learning_rate=0.001
python mnist_batch_size.py --batch_size=5 --learning_rate=0.01
python mnist_batch_size.py --batch_size=5 --learning_rate=0.1
python mnist_batch_size.py --batch_size=5 --learning_rate=1.0
python mnist_batch_size.py --batch_size=50 --learning_rate=0.01
python mnist_batch_size.py --batch_size=50 --learning_rate=0.1
python mnist_batch_size.py --batch_size=50 --learning_rate=1.0
python mnist_batch_size.py --batch_size=50 --learning_rate=10.0
python mnist_batch_size.py --batch_size=500 --learning_rate=0.01
python mnist_batch_size.py --batch_size=500 --learning_rate=0.1
python mnist_batch_size.py --batch_size=500 --learning_rate=1.0
python mnist_batch_size.py --batch_size=500 --learning_rate=10.0
python mnist_batch_size.py --batch_size=5000 --learning_rate=0.1
python mnist_batch_size.py --batch_size=5000 --learning_rate=1.0
python mnist_batch_size.py --batch_size=5000 --learning_rate=10.0
