python mnist_layers_activations.py --layers=1 --activation=none
python mnist_layers_activations.py --layers=1 --activation=relu
python mnist_layers_activations.py --layers=1 --activation=tanh
python mnist_layers_activations.py --layers=1 --activation=sigmoid
python mnist_layers_activations.py --layers=10 --activation=none
python mnist_layers_activations.py --layers=10 --activation=relu
python mnist_layers_activations.py --layers=10 --activation=tanh
python mnist_layers_activations.py --layers=10 --activation=sigmoid
python mnist_layers_activations.py --layers=2 --activation=sigmoid
python mnist_layers_activations.py --layers=5 --activation=sigmoid
python mnist_layers_activations.py --layers=8 --activation=sigmoid
